# Docker Compose 配置文件
version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: ai-hub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ai_hub
      MYSQL_USER: aihub
      MYSQL_PASSWORD: aihubpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - ai-hub-network
    restart: unless-stopped

  # AI Hub API 服务器
  api:
    build: .
    container_name: ai-hub-api
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mysql
      DB_USER: aihub
      DB_PASSWORD: aihubpassword
      DB_NAME: ai_hub
      JWT_SECRET: your_super_secret_jwt_key_change_in_production
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - ai-hub-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: ai-hub-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - ai-hub-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  ai-hub-network:
    driver: bridge
